### ISSUE TITLE
Missing precondition failure codes

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#103]
`RefactoringStatus`es should have at minimum the precondition failure code.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/852345538580428)

**Comment by khatchad** [comment]
![img_20181018_142641143](https://user-images.githubusercontent.com/2048831/47175825-174a7e80-d2e2-11e8-9696-e2460a446c28.jpg)

**Comment by khatchad** [comment]
We should see this in the evaluation. @walleXD could you please verify that you are seeing these error codes in the statuses?

**Comment by khatchad** [comment]
@walleXD If you could paste a CSV sample here, that would be helpful.

**Comment by orenwf** [comment]
Think this belongs in a separate Evaluation Milestone ?
