### ISSUE TITLE
Java Problem: The import java.util.HashSet is never used

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#104]
Resource: edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/Entity.java
Location: line 3

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/853906446536823)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/47c30cdce2045f3020c4cbb9ce709e8cc4a9132c
