### ISSUE TITLE
Java Problem: Type safety: The method add(int, Object) belongs to the raw type List. References to generic type List<E> should be parameterized

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#105]
Resource: edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/Entity.java
Location: line 180

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/853917750624278)

**Comment by orenwf** [comment]
Not sure how to address this. The eclipse API here is built with Non-generic collections as in many other places. 

```
ParameterizedType parameterized = ast.newParameterizedType(ast.newSimpleType(ast.newSimpleName("Optional")));
Type parameter = ast.newSimpleType(ast.newSimpleName(rawType));
parameterized.typeArguments().add(0, parameter);
```
could become:
```		
ParameterizedType parameterized = ast.newParameterizedType(ast.newSimpleType(ast.newSimpleName("Optional")));
Type parameter = ast.newSimpleType(ast.newSimpleName(rawType));
((List<Type>)parameterized.typeArguments()).add(0, parameter);
```

But we still get a warning about an unchecked cast.
