### ISSUE TITLE
Seeder should report errors

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#122]
If you don't have an `IJavaElement`, leave it out of the `RefactoringStatus`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877640906166603)

**Comment by orenwf** [comment]
Fixed by: https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/eb751ab109941963d76d11885484cb5a3fd72855
