### ISSUE TITLE
IJavaElement should be stored in the refactoring status entry

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#123]
Like [this](https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L196-L199), so we can retrieve it later like [this](https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.eval/src/edu/cuny/citytech/defaultrefactoring/eval/handlers/EvaluateMigrateSkeletalImplementationToInterfaceRefactoringHandler.java#L343-L360).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877659509498645)

**Comment by khatchad** [comment]
@walleXD would also find this interesting.

**Comment by orenwf** [comment]
[Implemented here.](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/master/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/N2ORefactoringStatusContext.java)
```
public class N2ORefactoringStatusContext extends RefactoringStatusContext {
...
	public N2ORefactoringStatusContext(final IJavaElement element, final ISourceRange range,
			final EnumSet<PreconditionFailure> failures) {
		this.element = element;
		this.sourceRange = range;
		this.preconditionFailures = failures;
	}
...
	@Override
	public Object getCorrespondingElement() {
		return this.element;
	}
...
}
```
and then use like this:
```
for (RefactoringStatusEntry e : RefactoringStatus.getEntries()) {
	N2OStatusContext ctx = (N2OStatusContext)e.getContext();
	SomeElementProcessing.apply((IJavaElement)ctx.getCorrespondingElement())
}
```
