### ISSUE TITLE
Overuse of factory methods

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#124]
They really only should be used in cases where ctors don't suffice, i.e., when a subclass can be returned.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/9eed127b1fd90a8cac72e77c6cae7b7228e19a0d/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/ConvertNullToOptionalRefactoringProcessor.java#L328

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877666397713606)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/cccb80bdf7866b67f815cfbb85a190c490a88d22#diff-fe5d2119f6dfbadbb775088f0acd8643
