### ISSUE TITLE
Stream misuse

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#125]
You don't need to collect to call `forEach()`. Just call `forEach()` w/o collecting.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/9eed127b1fd90a8cac72e77c6cae7b7228e19a0d/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/Entities.java#L63-L65

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877674648707312)

**Comment by orenwf** [comment]
fixed in https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/07a917fb35567bc815bf2e5dd4ac7f099c765eaf
