### ISSUE TITLE
Public fields used in a public class

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#126]
Please do not use public fields in public classes.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/9eed127b1fd90a8cac72e77c6cae7b7228e19a0d/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/Entities.java#L43-L46

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877680441458243)

**Comment by orenwf** [comment]
[Fixed.](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/89f2d26c62ac9a83d9f723598d3ad8372e49aec9/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/Instance.java#L12-L16)
