### ISSUE TITLE
One status context should be associated with one RefactoringStatusEntry

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#127]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/9eed127b1fd90a8cac72e77c6cae7b7228e19a0d/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/N2ORefactoringStatusContext.java#L15

Should be:
```java
private final PreconditionFailure preconditionFailures; 
```

1:1 mapping between `RefactoringStatusEntry` and `PreconditionFailure`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/877685876815947)

**Comment by orenwf** [comment]
Fixed in https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/07a917fb35567bc815bf2e5dd4ac7f099c765eaf
