### ISSUE TITLE
Expose Failed set count

### ISSUE THREAD

**Issue by walleXD** [ponder-lab/Null-to-Optional-Eclipse-Plugin#131]
In Evaluation, we need to count the number of elements which failed during seeding & propagation. Given that there is already a set where all the failed elements are added, all be need is to expose an getter method which return `int` size of that set

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/902313058394320)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/9a691c4dbe47a335a55ab4a0caaaa0bdfb04593c
