### ISSUE TITLE
CSV sample showing `PreconditionFailure` codes in the output

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Null-to-Optional-Eclipse-Plugin#133]
_Originally posted by @khatchad in https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/issues/103#issuecomment-434774756_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/903616264892627)

**Comment by khatchad** [comment]
I don't get it. Is this a problem?

**Comment by orenwf** [comment]
It's an issue, but related to Eval, not preconditions. The codes are there, and the Evaluator needs to use them now. I linked to the old issue for reference.

**Comment by walleXD** [comment]
Supersided by #35
