### ISSUE TITLE
Parameterized Types and Java Arrays

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Null-to-Optional-Eclipse-Plugin#136]
#105, #15, #64 

@khatchad 
```
Integer[] list = { null, 1 };
```
we would like this to become:
```
Optional<Integer>[] list = { Optional.empty(), Optional.of(1) };
```
but it can't because Java does not support Generic arrays.
The choice is to either create an `Object[]` or un-parameterized `Optional[]`, or not to transform it.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/905756815784140)

**Comment by khatchad** [comment]
Interesting. Does this help? https://stackoverflow.com/questions/529085/how-to-create-a-generic-array-in-java

**Comment by orenwf** [comment]
[branch](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/IterablesAndArrays/edu.cuny.hunter.optionalrefactoring.tests/test%20cases/edu/cuny/hunter/optionalrefactoring/ui/tests/ConvertNullToOptionalRefactoringTest.java)
