### ISSUE TITLE
Don't refactor generated code

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#14]
We should fail (i.e., we'll need to treat it like binary code) if we encounter generated code.

BTW, the Java model actually knows if elements are "generated." See the default method refactoring project for an example.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/721665034043626)

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

I don't think that's an accurate except to throw. It make be source code that is read-only.

**Comment by orenwf** [comment]
#71 
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L136-L149

**Comment by khatchad** [comment]
Dupe of #32?
