### ISSUE TITLE
Actually, this is not the refactorable elements but rather the number of passing element sets

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#146]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7399619b9cf1826bc9fcd400a05d88fd7fe86a45/edu.cuny.hunter.optionalrefactoring.eval/src/edu/cuny/hunter/optionalrefactoring/eval/handlers/EvaluateConvertNullToOptionalRefactoringHandler.java#L200

**Comment by walleXD** [comment]
Fixed in 57926f562d8e26c36440e9e1f823bc386c4b7c32
