### ISSUE TITLE
Deal with library calls

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#28]
See https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/issues/26#issuecomment-403539001. We also had a similar problem with [Constants-to-Enum-Eclipse-Plugin](https://github.com/ponder-lab/Constants-to-Enum-Eclipse-Plugin). How did we deal with that there? It is a bit different here for the following reasons:
- Here, we are going from reference type to reference type, so we need to consider altering dynamic dispatch.
- We have bridge methods for optionals.

A good first step would be to check out and document what is done in the enum case.

This should be part of the precondition milestone but will discuss. I try not to milestone anything that hasn't been discussed.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/738358020601618)

**Comment by khatchad** [comment]
Related to #37?

**Comment by khatchad** [comment]
@orenwf How are we on this one?

**Comment by orenwf** [comment]
The handler for this PreconditionFailure:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java#L161-L181

This PreconditionFailure is dealt with by returning a pair `(IJavaElement, RefactoringStatus)` to the `NullSeeder` or `RefactorableHarvester`. In the case of the `NullSeeder`:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L105-L114
A `TypeDependentElementSet` singleton "seed" is created with a `RefactoringStatus` with one `RefactoringStatus.FATAL_ERROR` entry.
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactorableHarvester.java#L124-L135
In the `RefactorableHarvester` only the "passing" seeds for which `RefactoringStatus.isOK()` evaluates to `true` are seeded into the WorkList for propagation.

In `RefactorableHarvester.process()` 
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactorableHarvester.java#L173-L195

The idea is that the catch blocks should remove the from the `workList` and `bridgeList` data structures any elements that are present when an exception carrying a `RefactoringStatus.FATAL_ERROR`, but only from the `workList` when an exception carrying a `RefactoringStatus.ERROR` is caught.

However, I am absolutely stumped and have been debugging all day and cannot get this to work correctly. Hopefully we can discuss this tomorrow. @khatchad

**Comment by khatchad** [comment]
I think this one is completed. @orenwf please update. I think we are bridging depending on options.

**Comment by orenwf** [comment]
Actually "bridging" is really related to the transformation. Precondition checking is completed for this case. [See Wiki.](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/wiki/Harvesting-Null-Dependent-Program-Elements)
