### ISSUE TITLE
Need some options

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#31]
- Refactor fields as optional?
- Consider implicit nullness for fields? (see #12).
- Refactor method return types?
- etc.

We should have such options available.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/738656333642400)

**Comment by orenwf** [comment]
This is done, integrated into master as per #60

**Comment by khatchad** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/issues/31#issuecomment-407576361
