### ISSUE TITLE
Fail for generated code

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#32]
Related to #26.

https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L1780-L1783

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/738680451536386)

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

[Oren Friedman](https://app.asana.com/0/565513407497635/565513407497635) what are the code changes that fixed this issue?

**Comment by orenwf** [comment]
#71 
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/AddressingPreconditionsSquashed/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java

**Comment by khatchad** [comment]
As discussed with @orenwf this case is non-fatal and should be treated just like the library (binary) case from our point of view.

**Comment by khatchad** [comment]
➤ Oren Friedman commented:

This is working in our current test cases, but additional test cases are probably in order. 
Just as with read-only nodes, and binary nodes, when generated code is encountered at the dependent node in an AST traversal from dependency -> dependent, the dependency node is added to a list of expressions to bridge, because it's dependency  will have its type changed to Optional<T> but it must still evaluate to the raw type in order to satisfy the type binding of the dependent, which cannot be changed.

**Comment by khatchad** [comment]
This code: 

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/9d575f6029c453207e432e936c55bf7927c4f3a5/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/utils/Util.java#L288-L340 looks very fragile. Please compare with:

https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L1780-L1783

See how there's no "kind" referenced at all? As usual, please move common methods up to the common framework if you want to reuse it.

**Comment by khatchad** [comment]
Use https://help.eclipse.org/luna/topic/org.eclipse.jdt.doc.isv/reference/api/org/eclipse/jdt/core/IJavaElement.html#getResource--.
