### ISSUE TITLE
Investigate differences between sets

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#34]
What is `notN2ORefactorable` and `notRefactorable` and how are they different?

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/3ea08db2ef437621596881da84a8d9a966f1663b/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactorableHarvester.java#L157-L169

**Comment by khatchad** [comment]
The questions we need answers to are as follows:
1. Where is `notN2ORefactorable` used after elements have been added to it?
1. Where is `notRefactorable` used after elements have been added to it?
1. How are they different?

**Comment by orenwf** [comment]
I've changed the names but:
`notRefactorable` -> sets of elements removed from the worklist for failing any precondition
`notN2Orefactorable` became `bridgeable` -> sets of elements that were removed from the worklist for failing a precondition but that can be bridged like a library call

**Comment by khatchad** [comment]
This makes sense.
