### ISSUE TITLE
Fail for non-source files

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Null-to-Optional-Eclipse-Plugin#37]
Remove a type dependent set from the work list during propagation if it depends on an element located in a `jar` file or `class` file. 
Is there a way to create a JUnit test that has a dependency on a `class` file or a `class` file contained in a `jar` file?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/740556832654990)

**Comment by khatchad** [comment]
> Is there a way to create a JUnit test that has a dependency on a class file or a class file contained in a jar file.

Yes:
```java
Object o = null;
System.out.println(o);
```
Here, the parameter of `OutputStream.println()` is the dependent entity, and it's in a jar.

**Comment by khatchad** [comment]
We should fail for this, just like we did in the enum case. Afterwards, though, we can explore bridging as previously discussed in https://app.asana.com/0/274838528047159/738996203798122.

**Comment by orenwf** [comment]
#71 
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/AddressingPreconditionsSquashed/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java

**Comment by khatchad** [comment]
Please review @orenwf. Should be bridgeable.

**Comment by orenwf** [comment]
[Explained here](
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/wiki/Harvesting-Null-Dependent-Program-Elements).
