### ISSUE TITLE
Plug-in not working on eclipse photon

### ISSUE THREAD

**Issue by yaziza** [ponder-lab/Null-to-Optional-Eclipse-Plugin#40]
The plug-in is not building with eclipse photon, i will investigate the cause.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/742105194822486)

**Comment by khatchad** [comment]
@orenwf Please see if the change outlined [here](https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring/commit/9796c44239f9007448dccaf538ac275b3b5b8c5a#diff-6a3371457528722a734f3c51d9238c13) fixes the problem. If it does, please update the documentation accordingly.

**Comment by khatchad** [comment]
Ah, actually, I didn't fix it on my own workspace. I just let it be and didn't run the tests *locally*.

**Comment by khatchad** [comment]
I see the problem. I imported `org.eclipse.jdt.ui.tests.refactoring` as a binary project and there's no top-level directory (e.g., `bin`):

![image](https://user-images.githubusercontent.com/2048831/45362125-f768c200-b5a1-11e8-865a-c8ce887eb9e0.png)

**Comment by orenwf** [comment]
Trying to do this workaround now, I've created the `bin` dir and moved `org` into it... not sure how to alter the classpath through eclipse to specifically add just the `org.eclipse.jdt.ui.tests.refactoring/bin` directory ... going to try it manually editing the `.classpath` files.

**Comment by orenwf** [comment]
I've now performed this workaround on a fresh install of Photon and it appears to be able to build.

**Comment by orenwf** [comment]
Submitted to Eclipse bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=538995

**Comment by khatchad** [comment]
@orenwf Please respond to https://bugs.eclipse.org/bugs/show_bug.cgi?id=538995#c4. Please also have a look at https://bugs.eclipse.org/bugs/show_bug.cgi?id=538995#c3.
