### ISSUE TITLE
Casting nulls may be a precondition failure

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#44]
Explicit casts may be a precondition failure. We need to think about this with some examples. We also need to consider implicit and explicit nullness.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/750070536688336)

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

[Oren Friedman](https://app.asana.com/0/565513407497635/565513407497635) where are we on this one? Do we have some test cases where casts are failing?

**Comment by orenwf** [comment]
I just finished them, and pushed to #53 

Tests are:
* https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/PreconditionsPropagation/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpression/in/A.java
* https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/PreconditionsPropagation/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpressionTransitiveVariable/in/A.java
* https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/PreconditionsPropagation/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpressionTransitiveMethod/in/A.java

**Comment by khatchad** [comment]
@orenwf Is throwing an exception that carries the failed ASTNode. Question: what is happening with the refactoring status?

**Comment by khatchad** [comment]
After discussing with @orenwf, here's the plan:
1. Remove [`ProgramEntity`](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/master/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/ProgramEntity.java).
1. Replace it with [this class](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/master/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/TypeDependentElementSet.java), but we will add a `RefactoringStatus` field.
1. What needs to happen is that the refactoring exceptions need to also carry a `RefactoringStatus` containing information about the error, i.e., the element causing the error. This should replace the ASTNode mechanism currently in place. There are many examples of this in our other plug-ins.
1. When the exception is caught in the main loop involving the workslist, the status needs to be merged with the status in the `TypeDependentElementSet` (which should be renamed to `ProgramEntity`).

This needs to be done because the `checkFinalPrecondition()` method *returns* a `RefactoringStatus`.

**Comment by khatchad** [comment]
Some examples of using `RefactoringStatus`:
- https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L1373-L1424
- https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring/blob/b3753532bf0d701d693c5ea10efff4d1c29a71ad/edu.cuny.hunter.streamrefactoring.core/src/edu/cuny/hunter/streamrefactoring/core/refactorings/OptimizeStreamsRefactoringProcessor.java#L265-L268

**Comment by orenwf** [comment]
in #71 
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/TypeDependentElementSet.java#L24-L77

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L63-L172

Still need to figure out exactly how to use this in the main propagation loop.

**Comment by orenwf** [comment]
Seeder throws an exception...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L227-L232
Catches the exception and calls the failure handler...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L99-L116
Returns a failing status to indicate the seed is no good...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java#L116-L127

Propagator throws an exception...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullPropagator.java#L628-L632
And here as well...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullPropagator.java#L787-L791
Caught here by the Harvester, which handles it by just trashing the worklist and the nullSeeds which is what we want...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactorableHarvester.java#L196-L209

**Comment by orenwf** [comment]
Tests are here:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpressionFailNoSeed/in/A.java#L1-L13
And here...
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpressionFailureMethod/in/A.java#L1-L14
And here.
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testCastExpressionFailureVariable/in/A.java#L1-L17

**Comment by khatchad** [comment]
Looking at https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/d881b4549846979f5ddf313dc988c25431e84d75/edu.cuny.hunter.optionalrefactoring.tests/test%20cases/edu/cuny/hunter/optionalrefactoring/ui/tests/ConvertNullToOptionalRefactoringTest.java#L324, I see that this is an error case, which is good. However, I am concerned that we are not testing the specific precondition failure. In other words, we know that it's an error, but for all we know, the error could be something completely unrelated to casting. It would be better to see something that checks specifically for https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/d881b4549846979f5ddf313dc988c25431e84d75/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java#L72.

**Comment by orenwf** [comment]
What you're saying makes sense. What we can do here is change the test code so that it checks for the presence of `CAST_EXPRESSION` inside the `RefactoringStatus`. This would require a slight rework of my exception handling both in the Seeder and in the Propagation phase, but it makes sense to use this enum in testing.

**Comment by khatchad** [comment]
I think what I'm saying is that there's a multiplicity problem. But, that may be fine as long as only one type dependent set fails per test.

**Comment by khatchad** [comment]
It is a precondition failure but the severity of which depends on the refactoring settings.

**Comment by khatchad** [comment]
@orenwf says that each precondition failure has a separate refactoring status entry (1:1 and onto mapping between failures and status entries).

**Comment by orenwf** [comment]
[See Wiki.](https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/wiki/Harvesting-Null-Dependent-Program-Elements)
