### ISSUE TITLE
Incorrect parameter type

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#55]
The `choices` parameter should not be a map as they key values are never used.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/acb2c5444ac02ee5a2283c9e288767852f33ef45/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactoringContextSettings.java#L35

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/756014158022359)

**Comment by orenwf** [comment]
We're rewriting the RefactoringContextSettings totally per #60

**Comment by orenwf** [comment]
Map<String,String> is what `System.getEnv()` gives us... 
We can either:
* put all the environmental variables on one key, and take them from the first entry
* put each one on separate keys with a true/false or even empty value

**Comment by khatchad** [comment]
@orenwf says this is will be in a new PR.

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/f767e453a48889b3bb14d3863f3a71b397104cfb/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/RefactoringContextSettings.java#L1-L58

**Comment by khatchad** [comment]
@orenwf Is it in the *master* branch?

**Comment by orenwf** [comment]
Now it is.
