### ISSUE TITLE
Performing the change should not be part of the refactoring options

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#57]
Not performing the transformation should be not be a refactoring option. It is just for us to execute only the analysis during the evaluation. You would never have a refactoring that doesn't do a transformation.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/acb2c5444ac02ee5a2283c9e288767852f33ef45/edu.cuny.hunter.optionalrefactoring.eval/src/edu/cuny/hunter/optionalrefactoring/eval/handlers/EvaluateConvertNullToOptionalRefactoringHandler.java#L153

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/756018191353919)

**Comment by orenwf** [comment]
This was semantics I was attempting to preserve from how I understood the streams project structure. Very possible I misunderstood it. I will get rid of this.

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/f767e453a48889b3bb14d3863f3a71b397104cfb/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/RefactoringContextSettings.java#L1-L58
