### ISSUE TITLE
Uninitialized primitive variable declarations are not implicitly null

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Null-to-Optional-Eclipse-Plugin#58]
They shouldn't be seeded.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/756023436028785)

**Comment by orenwf** [comment]
Right now they are being seeded/propagated incorrectly.

**Comment by orenwf** [comment]
This is fixed now.
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/b9ea12fa9713a78a1ebb7e57792101d16c47aee5/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L86-L103

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/Preconditions/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testImplicitlyNullVariableDecl/in/A.java

**Comment by orenwf** [comment]
Included in #53 
Ready for review. @khatchad

**Comment by orenwf** [comment]
#67

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/5aefff4d0006e53c4b347fa9133eb4da7792e2b6/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L122-L172

**Comment by orenwf** [comment]
Now in master:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/NullSeeder.java#L123-L139

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/aa715df8c65e02805866eff272faf1d821335150/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testSettingsImplicitOff/in/A.java#L1-L9
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/aa715df8c65e02805866eff272faf1d821335150/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testSettingsImplicitOn/in/A.java#L1-L8

**Comment by khatchad** [comment]
Really should be referencing *commits* that make these changes rather than source code locations.

**Comment by khatchad** [comment]
And, the commits should try to isolate said changes as much as possible.

**Comment by khatchad** [comment]
It's also a lot easier to document.

**Comment by khatchad** [comment]
➤ Oren Friedman commented:

This is addressed in the current master version and tests are passing. More tests may be needed.

**Comment by khatchad** [comment]
@orenwf Can you elaborate on which additional tests are needed? This makes the think that the code duplication is worse than we thought.

**Comment by orenwf** [comment]
This actually is fixed already. The test shows it working properly:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/eb751ab109941963d76d11885484cb5a3fd72855/edu.cuny.hunter.optionalrefactoring.tests/test%20cases/edu/cuny/hunter/optionalrefactoring/ui/tests/ConvertNullToOptionalRefactoringTest.java#L512-L515
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/eb751ab109941963d76d11885484cb5a3fd72855/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testSettingsImplicitOff/in/A.java#L1-L8
