### ISSUE TITLE
Current data structure for refactoring options is too complicated

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#60]
Please use an EnumSet.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/381307383182823)

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

Related to [Need some options](https://app.asana.com/0/274838528047159/738656333642400)

**Comment by orenwf** [comment]
Not too sure how to best use the EnumSet here. Where should it be instantiated and it's state maintained? In the RefactoringProcessor?

**Comment by orenwf** [comment]
Now in master:
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/7897e5b74a70c6a92ef2df3581bad671dfb2482e/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/RefactoringSettings.java#L1-L87

**Comment by orenwf** [comment]
This is now integrated into the plugin with tests beginning with `testSettings...`.

Here's one such:

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/aa715df8c65e02805866eff272faf1d821335150/edu.cuny.hunter.optionalrefactoring.tests/resources/ConvertNullToOptional/testSettingsFieldsOff/in/A.java#L1-L11

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

Thanks for taking care of this [Oren Friedman](https://app.asana.com/0/565513407497635/565513407497635). A pattern I have noticed is that you often seem to gravitate to complicated solutions.

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

Rather, please favor simpler solutions because they are easier to reason about its correctness and maintain. Please favor simple, elegant solutions when possible.

**Comment by khatchad** [comment]
➤ Raffi Khatchadourian commented:

This is a general observation and is not particular to this issue. The recommendation is also general.
