### ISSUE TITLE
Move analysis classes to the package edu.cuny.hunter.optionalrefactoring.core.analysis

### ISSUE THREAD

**Issue by orenwf** [ponder-lab/Null-to-Optional-Eclipse-Plugin#61]
It's only class is `PreconditionFailure.java`.

https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/master/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java

**Comment by khatchad** [comment]
That package is really only meant to hold refactorings (like refactoring processors) and data structures that are directly related. Anything that does code analysis should really be in the analysis package.

**Comment by orenwf** [comment]
Done per -> https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/pull/53/commits/33a6f79162c5a3360b848cac77a20f30bed6e535
