### ISSUE TITLE
UI removal didn't produce a coverage change

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#70]
Weird that there was no change in coverage here. Perhaps something isn't right with the setup.

Coverage remained the same on ponder-lab/Null-to-Optional-Eclipse-Plugin master at 44.86%

Created from Slack: https://cunyponder.slack.com/archives/G9B5Z0UD6/p1532902975000036

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/761601628853494)

**Comment by orenwf** [comment]
is it possible the UI module isnt set up for coverage ?

**Comment by orenwf** [comment]
Oh wait that was the point... ummm ... I dont think I had any tests for the UI .. could that be the reason?

**Comment by khatchad** [comment]
Yeah we shouldn't have any which is why I removed it as a dependence. We can look into it later.

**Comment by khatchad** [comment]
I thought it was set up. Have a look at the commit change.
