### ISSUE TITLE
Static imports should not be processed

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#77]
If the propagator tries to propagate a static import (e.g., as a return value of a method), skip it. It's not a failure, just move on.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/763991528984866)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/aa715df8c65e02805866eff272faf1d821335150/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/refactorings/RefactorableHarvester.java#L160-L196

the `if` statement now includes `&& ((IJavaElement) match.getElement()).getElementType() != IJavaElement.IMPORT_DECLARATION)` which should prevent this from running the `NullPropagator` on such elements. I haven't figured out how to write a test for this yet, but I've run it on the `Java-subjects` test cases that were giving the problem and it no longer comes up.

**Comment by khatchad** [comment]
Can't you have a test that has a static import?
