### ISSUE TITLE
Format source code

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#78]
Please use the built-in source code formatting in Eclipse and choose the Eclipse style.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/763991528984873)

**Comment by khatchad** [comment]
`edu.cuny.hunter.optionalrefactoring.ui.tests.NullToOptionalExpectedResult` is an example.

**Comment by khatchad** [comment]
In fact, is that class even needed? I don't see it referenced anywhere.

**Comment by ponder-sync** [comment]
➤ Raffi Khatchadourian commented:

We need to do this again.

**Comment by khatchad** [comment]
@orenwf Can we do this now? We should run in all branches.

**Comment by khatchad** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/4dd6a1a9f5061201d6eb9ee9f8fe37455e3885e1
