### ISSUE TITLE
Use specific logger or the one from Eclipse

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#89]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/aa715df8c65e02805866eff272faf1d821335150/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/PreconditionFailure.java#L101

We should not be using the anonymous logger but rather one that is specific to our application in some way. Here are some examples:

https://github.com/ponder-lab/Optimize-Java-8-Streams-Refactoring/blob/fcb1d9e2cb6cdebc9e099f99c6545fa5a827ec69/edu.cuny.hunter.streamrefactoring.core/src/edu/cuny/hunter/streamrefactoring/core/analysis/Stream.java#L94

https://github.com/ponder-lab/Migrate-Skeletal-Implementation-to-Interface-Refactoring/blob/1e76f282f6a6045bf7b4c4aafc9e646c3d340791/edu.cuny.citytech.defaultrefactoring.core/src/edu/cuny/citytech/defaultrefactoring/core/refactorings/MigrateSkeletalImplementationToInterfaceRefactoringProcessor.java#L526-L533

You'd pick one or the other. Again, any common code should go into the common framework.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/812512262328248)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/18f9dcc4b6fa7be6b7a9b9a37bdbf2a75a9dce7d
