### ISSUE TITLE
Need a test case with two fields

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#92]
In:
```java
class C {
    Object o;
    Object o2;
}
```
Out:
```java
import java.util.Optional;
class C {
    Optional<Object> o = Optional.empty();
    Optional<Object> o2 = Optional.empty();
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/820633361849366)

**Comment by ponder-sync** [comment]
➤ Raffi Khatchadourian commented:

Hey [Walee Ahmed](https://app.asana.com/0/821213886682204/list). I filed this issue during our demo. Maybe this would be a good start for you to start to understand the project. We can meet on Monday to discuss it if you are interested. Also, do you have a github username? If so, I can give you access.

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/4c57db7039d54c4a11b4abbacbab388d86dc14e4
