### ISSUE TITLE
Implicitly null fields need an initializer Optional.empty()

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#93]
Except for cases where *every* ctor initializes the field.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/820639404054494)

**Comment by orenwf** [comment]
This is now addressed by #95

**Comment by ponder-sync** [comment]
➤ Raffi Khatchadourian commented:

I will review.
