### ISSUE TITLE
Document Options for Preconditions

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#99]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/blob/753963ec9a08fa631c1c0a59f359c7b1e64bffd2/edu.cuny.hunter.optionalrefactoring.core/src/edu/cuny/hunter/optionalrefactoring/core/analysis/RefactoringSettings.java#L13-L23

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/841440908991679)

**Comment by orenwf** [comment]
https://github.com/ponder-lab/Null-to-Optional-Eclipse-Plugin/commit/63eb0b0947466bc086efe1f7fd7e0a08d0f4b1a1
